# Generated by Django 4.0.3 on 2022-04-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ecommerce', '0002_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
