# Generated by Django 4.0.3 on 2022-04-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ecommerce', '0004_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
